version: '3'

services:
  mongo:
    image: mongo
    
  jguweka:
    image: dockerhubuser/jguweka:OAS3
    links:
      - "mongo:mongodb"
    ports:
      - "8849"
    depends_on:
      - mongo

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - jguweka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - jguweka
    ports:
      - "80:80"
